-- SQL diff generated by compare_seed_with_db.php
SET FOREIGN_KEY_CHECKS=0;

UPDATE `products` SET `colors`='Black, Navy, Charcoal',`sizes`='S, M, L, XL' WHERE `id`='2';
UPDATE `products` SET `colors`='Floral Blue, Floral Pink',`sizes`='S, M, L',`gallery`='["\/assets\/products\/gallery_68f25374569a1.png","\/assets\/products\/gallery_68f2537457217.png","\/assets\/products\/gallery_68f2537457cfd.png","\/assets\/products\/gallery_68f2537458163.png"]' WHERE `id`='11';
UPDATE `products` SET `colors`='Black, Navy, Wine Red',`sizes`='S, M, L',`gallery`='["\/assets\/products\/gallery_68f252f4eefe4.png","\/assets\/products\/gallery_68f252f4efbe1.png","\/assets\/products\/gallery_68f252f4f0262.png","\/assets\/products\/gallery_68f252f4f06b7.png"]' WHERE `id`='12';

SET FOREIGN_KEY_CHECKS=1;
